### PR TITLE
U1-50 Write unit test for helper function filter-images

### PR DESCRIPTION
**Pull request by huyhqit**
Jira ticket: https://pass-career.atlassian.net/projects/U1/issues/U1-50

### CODE REVIEW

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/unit/helpers/filter-images.test.js  1
         

Clones added
============
- tests/unit/helpers/filter-images.test.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4947667&bid=16354143)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/filter-unique-images.js  23
+ source/helpers/create-images-folder.js  33
+ source/helpers/arguments-prompt.js  9
+ source/helpers/get-files.js  42
+ source/helpers/task-executor.js  33
+ source/helpers/set-save-path.js  80
+ source/helpers/is-landscape-image.js  100
+ source/helpers/hash-bulk-file.js  66
+ source/helpers/copy-bulk-files.js  22
+ source/helpers/prompt-condition-match.js  50
+ source/helpers/index.js  100
+ source/helpers/get-save-path.js  37
+ source/helpers/normalize-path.js  20
+ source/helpers/hash-file.js  66
+ source/helpers/copy-file.js  57
+ source/helpers/filter-images.js  100
+ source/helpers/trim-quotes.js  50
         

Complexity increasing per file
==============================
- tests/unit/helpers/filter-images.test.js  1
         

Clones added
============
- tests/unit/helpers/filter-images.test.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4947667&bid=16354143)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/unit/helpers/filter-images.test.js  1
         

Clones added
============
- tests/unit/helpers/filter-images.test.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4947667&bid=16354143)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-landscape-image.js  100
+ source/helpers/index.js  100
+ source/helpers/arguments-prompt.js  9
+ source/helpers/get-save-path.js  37
+ source/helpers/get-files.js  42
+ source/helpers/filter-images.js  100
+ source/helpers/set-save-path.js  80
+ source/helpers/prompt-condition-match.js  50
+ source/helpers/task-executor.js  33
+ source/helpers/hash-bulk-file.js  66
+ source/helpers/trim-quotes.js  50
+ source/helpers/filter-unique-images.js  23
         

Clones added
============
- tests/unit/helpers/filter-images.test.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4947667&bid=16354143)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/filter-images.js  100
+ source/helpers/is-landscape-image.js  100
         

Clones added
============
- tests/unit/helpers/filter-images.test.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4947667&bid=16354143)

**Review by duyphaphach — APPROVED** [review]

**Pull request merged**
