### PR TITLE
U1-78 Write unit test for action get-images

### PR DESCRIPTION
**Pull request by huyhqit**
JIRA ticket: https://pass-career.atlassian.net/projects/U1/issues/U1-78

### CODE REVIEW

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/actions/get-images.js  25
         

Clones added
============
- tests/unit/actions/get-images.test.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4998860&bid=16496364)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/actions/get-images.js  34
         

Clones added
============
- tests/unit/actions/get-images.test.js  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4998860&bid=16496364)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/actions/get-images.js  30
         

Clones added
============
- tests/unit/actions/get-images.test.js  14
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4998860&bid=16496364)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/actions/get-images.js  30
         

Clones added
============
- tests/unit/actions/get-images.test.js  14
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4998860&bid=16496364)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/actions/get-images.js  30
         

Clones added
============
- tests/unit/actions/get-images.test.js  12
- tests/unit/actions/show-settings.test.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4998860&bid=16496364)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/actions/get-images.js  30
         

Clones added
============
- tests/unit/actions/show-settings.test.js  3
- tests/unit/actions/get-images.test.js  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4998860&bid=16496364)

**Review by duyphaphach — APPROVED** [review]

**Pull request merged**
