### PR TITLE
U1-35 Planning the test writing for U1

### PR DESCRIPTION
**Pull request by huyhqit**
JIRA Ticket: https://pass-career.atlassian.net/browse/U1-35

### CODE REVIEW

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/unit-tests/helpers/is-valid-size-image.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-valid-size-image.js  34
         

Complexity increasing per file
==============================
- tests/integration/get-lock-screen-image.test.js  1
- tests/unit-tests/helpers/is-valid-size-image.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-valid-size-image.js  34
         

Complexity increasing per file
==============================
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/integration/get-image.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-valid-size-image.js  34
         

Complexity increasing per file
==============================
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/integration/get-images.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-valid-size-image.js  34
         

Complexity increasing per file
==============================
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/integration/get-images.test.js  1
- tests/unit/helpers/reformat-date.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-valid-size-image.js  34
         

Complexity increasing per file
==============================
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/unit/helpers/reformat-date.test.js  1
- tests/integration/get-images.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/unit/helpers/reformat-date.test.js  1
- tests/integration/get-images.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/integration/get-images.test.js  1
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/unit/helpers/reformat-date.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/unit/helpers/reformat-date.test.js  1
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/integration/get-images.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-valid-size-image.js  34
         

Complexity increasing per file
==============================
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/unit/helpers/reformat-date.test.js  1
- tests/integration/get-images.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-valid-size-image.js  34
         

Complexity increasing per file
==============================
- tests/unit/helpers/is-valid-size-image.test.js  1
- tests/unit/helpers/reformat-date.test.js  1
- tests/integration/get-images.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ source/helpers/is-valid-size-image.js  34
         

Complexity increasing per file
==============================
- tests/integration/get-images.test.js  1
- tests/unit/helpers/reformat-date.test.js  1
- tests/unit/helpers/is-valid-size-image.test.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4866175&bid=16137391)

**Review by duyphaphach — APPROVED** [review]

**Pull request merged**
