### PR TITLE
U1-75 Detect running environment to show "Enter key to exit"

### PR DESCRIPTION
**Pull request by duyphaphach**
JIRA Ticket: https://pass-career.atlassian.net/browse/U1-75

### CODE REVIEW

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/helpers/filter-images.test.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4981139&bid=16450859)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/helpers/filter-images.test.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4981139&bid=16450859)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/unit/helpers/filter-images.test.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4981139&bid=16450859)

**Comment by knightus** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- source/actions/get-images.js  -2
- source/actions/random-desktop.js  -3
         

Clones added
============
- tests/unit/helpers/filter-images.test.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/pass-team/windows-10-lock-screen-image-extractor/pullRequest?prid=4981139&bid=16450859)

**Review by huyhqit — APPROVED** [review]

**Pull request merged**
